import Property from '../models/Property.model.js';
import Bed from '../models/Bed.model.js';
import Room from '../models/Room.model.js';
import Invoice from '../models/Invoice.model.js';
import axios from 'axios';

// WHY: This service contains pure business domain logic for financial operations.
// By isolating calculations here, we keep controllers thin and reusable.
export const generateMonthlyInvoices = async (propertyId, billingPeriod) => {
    // 1. Fetch the target property to check its global configurations
    const property = await Property.findById(propertyId);
    if (!property) throw new Error('Property configuration target not found');

    // 2. Locate all rooms under this building
    const rooms = await Room.find({ propertyId });
    const roomIds = rooms.map(r => r._id);

    // 3. Find all occupied beds in those rooms to know who to bill
    const occupiedBeds = await Bed.find({ roomId: { $in: roomIds }, isOccupied: true });

    const invoicesCreated = [];

    // 4. Loop through every single occupied bed to draft individual invoices
    for (const bed of occupiedBeds) {
        let finalElectricityCharge = 0;

        // WHY: Check our Modular Feature Toggle. If enabled, calculate power sub-meter splits.
        if (property.settings?.enablePerRoomElectricityBilling) {
            // For this beginner phase, we fetch a default standard modular split.
            // In Week 4, this reads dynamically from the logged consumption dashboard values.
            finalElectricityCharge = property.settings.electricityRatePerUnit * 5;
        }

        // WHY: Calculate base rent parameters. 
        // If the invoice is already generated by a duplicate run, the compound unique index handles protection.
        const baseRentAmount = property.settings?.baseSecurityDeposit || 5000;

        const invoice = await Invoice.create({
            tenantId: bed.currentTenantId,
            propertyId: propertyId,
            billingPeriod: billingPeriod, // e.g., "2026-07"
            baseRent: baseRentAmount,
            electricityCharges: finalElectricityCharge,
            paymentStatus: 'Pending',
        });

        invoicesCreated.push(invoice);
    }

    return invoicesCreated;
};

// WHY: Simulates triggering an external communications webhook to dispatch payment alerts to tenants.
export const triggerWhatsAppReminder = async (invoiceId) => {
    const invoice = await Invoice.findById(invoiceId).populate('tenantId');
    if (!invoice || !invoice.tenantId) throw new Error('Invoice or linked tenant records are missing');

    const tenantPhone = invoice.tenantId.phone;
    const totalDue = invoice.baseRent + invoice.electricityCharges + invoice.lateFees;

    // WHY: Construct a dynamic deeply linked billing payment payload string
    const upiDeepLink = `upi://pay?pa=property@vpa&pn=PGManagement&am=${totalDue}&cu=INR`;

    const webhookPayload = {
        to: tenantPhone,
        message: `Dear ${invoice.tenantId.name}, your rent invoice for ${invoice.billingPeriod} is pending. Total Outstanding: ₹${totalDue}. Tap link to pay instantly via UPI: ${upiDeepLink}`,
    };

    try {
        // WHY: Simulate hitting a live mock external messaging infrastructure API sandbox hub
        console.log(`[Webhook Trigger] Post payload out to WhatsApp gateway:`, webhookPayload);
        // Real integration example: await axios.post('https://api.whatsapp-provider.com/v1/send', webhookPayload);
        return true;
    } catch (error) {
        console.error(`[Webhook Failure] Notification engine sync issues:`, error.message);
        return false;
    }
};